### ISSUE TITLE
API Credentials

### ISSUE THREAD

**Issue by kurtbradd** [ruiramos/greatdj#9]
Might I suggest storing your credentials outside version control, and importing them inside a "secrets" file.

Soundcloud Client-ID found at greatdj/src/app.js
Youtube API-Key found at greatdj/src/utils/Api.js

**Comment by ruiramos** [comment]
Thanks Kurt, absolutely right.
I already do something similar to store the server side keys I'm using, just pushed a version that has has client side keys in a separated gitignored file. :+1:
